# Generated by Django 2.2.7 on 2019-11-04 11:53

from django.db import migrations
import django_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img_profile',
            field=django_fields.fields.DefaultStaticImageField(blank=True, upload_to='user', verbose_name='프로필 이미지'),
        ),
    ]
